# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: (Deprecation) Catch and report renamed settings
  ansible.builtin.fail:
    msg: >-
      Your configuration contains a variable, which now has a different name.
      Please change your configuration to rename the variable (`{{ item.old }}` -> `{{ item.new }}`).
  when: "item.old in vars"
  with_items:
    - { "old": "mongodb_systemd_required_systemd_services_list_default", "new": "mongodb_systemd_required_services_list_default" }
    - { "old": "mongodb_systemd_required_systemd_services_list_auto", "new": "mongodb_systemd_required_services_list_auto" }
    - { "old": "mongodb_systemd_required_systemd_services_list_custom", "new": "mongodb_systemd_required_services_list_custom" }
    - { "old": 'mongodb_config_mongosh_enableTelemetry', "new": "mongodb_config_mongosh_telemetry_enabled" }
    - { "old": 'mongodb_config_path', "new": "<Removed>" }

- name: Fail if required MongoDB settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`).
  when: "vars[item] == ''"
  with_items:
    - mongodb_identifier
    - mongodb_uid
    - mongodb_gid
    - mongodb_container_network
